### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by DaRkLoL1** [AkhmadBabaev/ordinary-slider#16]
![Скриншот 24-03-2020 11_22_58](https://user-images.githubusercontent.com/32780725/77403829-df424780-6dc1-11ea-9792-88f7dc914014.png)
Добавь эти команды в README и почему у тебя не видно в ней диаграммы)

**Comment by AkhmadBabaev** [comment]
Команды и диаграмма находятся в файле [DEVELOPERS-GUIDE.md](https://github.com/AkhmadBabaev/ordinary-slider/blob/master/DEVELOPERS-GUIDE.md).

**Comment by DaRkLoL1** [comment]
добавь тогда ссылку на другой редми и добавь возможность вызвать линтер через npm
